### ISSUE TITLE
Scrolling when specifying the parent breaks the picker

### ISSUE THREAD

**Issue by VincentMolinie** [mdbassit/Coloris#18] opened 2021-11-09 20:29 UTC
# Description of the issue
When I specify the option `parent`, and scroll the picker follow the parent but when I then click to choose a color it's most of the time black. It's due to the fact that it register the click like if the picker was positionned when first displayed (not after the scroll). It works fine when not specifying the `parent` option but then the scroll doesn't work 😅

**Comment by mdbassit** [comment] 2021-11-10 00:31
That's interesting, I specifically fixed that issue several weeks ago and I'm unable to reproduce it now. Can you please provide a test case where you can reproduce this issue?

**Comment by mdbassit** [comment] 2021-11-22 10:25
@VincentMolinie Is your issue resolved? Should I close this?

**Comment by mdbassit** [comment] 2021-12-07 01:16
I'm closing this for lack of activity.

**Closed by mdbassit** 2021-12-07 01:16 UTC
Labels: bug
