### ISSUE TITLE
Color picker not working while changing location

### ISSUE THREAD

**Issue by Kazem-ma79** [mdbassit/Coloris#23] opened 2021-11-21 20:07 UTC
I put input in a center aligned flex division but clr-picker is out of my div.
when removing it's top and left style, it's in correct position but color picker not working fine and should use it's previous position to select color.

Update: I want color picker to be always visible.

**Comment by melloware** [comment] 2021-11-21 22:23
Can you provide and html snippet or code sandbox reproducer so we can see the issue?

**Comment by Kazem-ma79** [comment] 2021-11-22 08:01
> Can you provide and html snippet or code sandbox reproducer so we can see the issue?

```

<body>
    <div class="container">
        <div class="colorContainer">
            <div>
                <input type="text" class="clr" value="rgb(255, 0, 0)">
                <p id="valueRGB"></p>
                <button id="parser">Parse</button>
            </div>
        </div>

.colorContainer {
    display: flex;
    overflow: scroll;
    width: 80vw;
    height: 80vh;
}

.clr {
    opacity: 0;
}

```
and removed top, left, position of #clr-picker element.

**Comment by mdbassit** [comment] 2021-11-22 10:24
> Update: I want color picker to be always visible.

Unfortunately, this color picker is not designed to be always visible, and It will take a lot of hacky tricks to make that happen. If you absolutely need a color picker that's always visible, I don't think this tool is right for you.

If you explain clearly what you are trying to achieve, we might be able to help.

**Comment by Kazem-ma79** [comment] 2021-11-22 10:35
> > Update: I want color picker to be always visible.
> 
> Unfortunately, this color picker is not designed to be always visible, and It will take a lot of hacky tricks to make that happen. If you absolutely need a color picker that's always visible, I don't think this tool is right for you.
> 
> If you explain clearly what you are trying to achieve, we might be able to help.

I couldn't find another tool and this one is very beautiful.
My project has a color picker as the main part and some other input components, if I use a hidden color picker my UI looks very empty. So I need a always visible color picker.
This is okay but only problem is that when I remove it's left & top style rules, the picker gets corrupted and need to move mouse outside of color picker to change the color.

**Comment by mdbassit** [comment] 2021-11-22 11:02
Here is a modified version that doesn't hide the picker [coloris-static.zip](https://github.com/mdbassit/Coloris/files/7580378/coloris-static.zip).

**Comment by jepsar** [comment] 2021-12-03 09:31
For me, having a static color picker would be a great feature. From my side a +1 on that.

**Comment by mdbassit** [comment] 2021-12-07 01:18
Since you opened another issue for this topic, I will close this one.

**Closed by mdbassit** 2021-12-07 01:18 UTC
